alertmanager:
  config:
    global:
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'devopscloudvoice@gmail.com'
      smtp_auth_username: 'devopscloudvoice@gmail.com'
      smtp_auth_password: '{{ env "SMTP_AUTH_PASSWORD" }}'
      smtp_require_tls: true

    route:
      receiver: 'email-alert'
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h

    receivers:
      - name: 'email-alert'
        email_configs:
          - to: 'babulunamaziah@gmail.com'

  alertmanagerSpec:
    extraEnvFrom:
      - secretRef:
          name: alertmanager-gmail-secret
