apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-pod-alert-rules
  namespace: monitoring
data:
  pod.rules.yaml: |
    groups:
    - name: pod.rules
      rules:

      # Alert if pod is not Running or Succeeded (Deleted pods usually disappear, so we alert on not Running/Succeeded)
      - alert: PodNotRunning
        expr: kube_pod_status_phase{phase!~"Running|Succeeded"} > 0
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is in status {{ $labels.phase }}"
          description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} has status {{ $labels.phase }} for more than 1 minute."

      # Alert if pod restarts frequently (optional, useful)
      - alert: PodRestartingFrequently
        expr: increase(kube_pod_container_status_restarts_total[10m]) > 3
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is restarting frequently"
          description: "Pod {{ $labels.pod }} has restarted more than 3 times in the last 10 minutes."
