apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
    - name: http
      port: 3000         # Port exposed inside the cluster
      targetPort: 3000   # Port on the container
      nodePort: 31000    # Optional: Node port to access the service externally
